export const actionLabels = {
  CONFIG_LOADED_SUCCESSFULLY: 'CONFIG_LOADED_SUCCESSFULLY',
  GENERATION_PARAMS_NUMBER_OF_TREES_CHANGED: 'GENERATION_PARAMETERS_CHANGED',
  GENERATE_FOREST: 'GENERATE_FOREST'
}