export const actionLabels = {
  CONFIG_LOADED_SUCCESSFULLY: 'CONFIG_LOADED_SUCCESSFULLY',
  GENERATION_PARAMS_CHANGED: 'GENERATION_PARAMETERS_CHANGED',
  FOREST_GENERATION_STARTED: 'FOREST_GENERATION_STARTED',
  FOREST_GENERATION_PROGRESSED: 'FOREST_GENERATION_PROGRESSED',
  FOREST_GENERATION_FINISHED: 'FOREST_GENERATION_FINISHED'
}